-- 운영 DB 적용은 사용자가 Supabase SQL editor에서 수동 실행해야 함.
-- Atomic sliding-window counters for high-cost API abuse protection.

create table if not exists public.api_usage (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  action text not null,
  subject_type text not null,
  subject_key_hash text not null
);

create index if not exists api_usage_lookup_idx
  on public.api_usage(action, subject_type, subject_key_hash, created_at desc);

create index if not exists api_usage_created_at_idx
  on public.api_usage(created_at);

alter table public.api_usage enable row level security;

revoke all on table public.api_usage from anon, authenticated;
grant all on table public.api_usage to service_role;

create or replace function public.consume_api_usage(
  p_action text,
  p_subject_type text,
  p_subject_key_hash text,
  p_window_seconds integer,
  p_limit integer
)
returns table (
  allowed boolean,
  current_count bigint,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usage_id bigint;
  v_count bigint;
  v_oldest timestamptz;
  v_now timestamptz := now();
begin
  if p_action is null or length(p_action) = 0
    or p_subject_type is null or length(p_subject_type) = 0
    or p_subject_key_hash is null or length(p_subject_key_hash) = 0
    or p_window_seconds <= 0
    or p_limit <= 0 then
    raise exception 'Invalid API usage counter parameters.';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      p_action || ':' || p_subject_type || ':' || p_subject_key_hash,
      0
    )
  );

  delete from public.api_usage
  where created_at < v_now - interval '8 days';

  insert into public.api_usage (
    action,
    subject_type,
    subject_key_hash,
    created_at
  ) values (
    p_action,
    p_subject_type,
    p_subject_key_hash,
    v_now
  )
  returning id into v_usage_id;

  select count(*), min(created_at)
  into v_count, v_oldest
  from public.api_usage
  where action = p_action
    and subject_type = p_subject_type
    and subject_key_hash = p_subject_key_hash
    and created_at > v_now - make_interval(secs => p_window_seconds);

  if v_count > p_limit then
    delete from public.api_usage where id = v_usage_id;

    return query
    select
      false,
      v_count - 1,
      greatest(
        1,
        ceil(
          extract(epoch from (
            v_oldest + make_interval(secs => p_window_seconds) - v_now
          ))
        )::integer
      );
    return;
  end if;

  return query select true, v_count, 0;
end;
$$;

revoke all on function public.consume_api_usage(text, text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_api_usage(text, text, text, integer, integer)
  to service_role;
