-- 운영 DB 적용은 사용자가 Supabase SQL editor에서 수동 실행해야 함.
-- Canonical, idempotent baseline for analysis history, purchases, and paid unlock RLS.

create table if not exists public.analysis_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  analysis_type text not null,
  image_url text,
  address text,
  metadata jsonb not null default '{}'::jsonb,
  result jsonb not null,
  remedy_art_url text,
  interior_remedy_art_url text,
  interior_style_id text,
  zodiac_image_url text,
  to_be_image_url text,
  feng_shui_score integer
);

alter table public.analysis_history
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists analysis_type text,
  add column if not exists image_url text,
  add column if not exists address text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists result jsonb,
  add column if not exists remedy_art_url text,
  add column if not exists interior_remedy_art_url text,
  add column if not exists interior_style_id text,
  add column if not exists zodiac_image_url text,
  add column if not exists to_be_image_url text,
  add column if not exists feng_shui_score integer;

alter table public.analysis_history
  drop constraint if exists analysis_history_analysis_type_check;
alter table public.analysis_history
  add constraint analysis_history_analysis_type_check
  check (analysis_type in ('internal', 'external'));

alter table public.analysis_history
  drop constraint if exists analysis_history_interior_style_id_check;
alter table public.analysis_history
  add constraint analysis_history_interior_style_id_check
  check (
    interior_style_id is null
    or interior_style_id in (
      'art_nouveau',
      'bauhaus',
      'art_deco',
      'midcentury',
      'renaissance',
      'impressionist',
      'ukiyoe',
      'cinematic_anime'
    )
  );

create index if not exists idx_analysis_history_user
  on public.analysis_history(user_id, created_at desc);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  order_id text not null,
  payment_key text,
  amount integer not null default 0,
  order_type text not null,
  status text not null default 'PENDING',
  buyer_name text,
  contact_info text,
  analysis_id uuid references public.analysis_history(id) on delete set null,
  refunded_at timestamptz,
  analysis_scope text,
  product_sku text
);

alter table public.purchases
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists order_id text,
  add column if not exists payment_key text,
  add column if not exists amount integer not null default 0,
  add column if not exists order_type text,
  add column if not exists status text not null default 'PENDING',
  add column if not exists buyer_name text,
  add column if not exists contact_info text,
  add column if not exists analysis_id uuid references public.analysis_history(id) on delete set null,
  add column if not exists refunded_at timestamptz,
  add column if not exists analysis_scope text,
  add column if not exists product_sku text;

alter table public.purchases
  drop constraint if exists purchases_analysis_scope_check;
alter table public.purchases
  add constraint purchases_analysis_scope_check
  check (analysis_scope is null or analysis_scope in ('internal', 'external'));

alter table public.purchases
  drop constraint if exists purchases_product_sku_check;
alter table public.purchases
  add constraint purchases_product_sku_check
  check (
    product_sku is null
    or product_sku ~ '^(internal|external)_(report|remedy|zodiac|frame|object)$'
  );

-- Required by all provider upserts that use onConflict: 'order_id'.
do $$
begin
  if exists (
    select 1
    from public.purchases
    where order_id is not null
    group by order_id
    having count(*) > 1
  ) then
    raise exception 'Cannot add purchases.order_id UNIQUE constraint: duplicate order_id rows must be resolved first.';
  end if;
end $$;

alter table public.purchases
  drop constraint if exists purchases_order_id_unique;
alter table public.purchases
  add constraint purchases_order_id_unique unique (order_id);

create index if not exists purchases_order_id_idx
  on public.purchases(order_id);
create index if not exists purchases_refunded_at_idx
  on public.purchases(refunded_at);
create index if not exists purchases_product_sku_idx
  on public.purchases(product_sku);

alter table public.analysis_history enable row level security;

drop policy if exists "Users can view own history" on public.analysis_history;
create policy "Users can view own history"
  on public.analysis_history for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own history" on public.analysis_history;
create policy "Users can insert own history"
  on public.analysis_history for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own history" on public.analysis_history;
create policy "Users can delete own history"
  on public.analysis_history for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can update own history" on public.analysis_history;
create policy "Users can update own history"
  on public.analysis_history for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

alter table public.purchases enable row level security;

drop policy if exists "Users can view own purchases" on public.purchases;
create policy "Users can view own purchases"
  on public.purchases for select
  using (auth.uid() = user_id);

drop policy if exists "Admin can view purchases" on public.purchases;
-- PostgreSQL RLS cannot read Vercel's ADMIN_EMAIL. Keep this SQL literal aligned
-- manually with ADMIN_EMAIL when the administrator account changes.
create policy "Admin can view purchases"
  on public.purchases for select
  using ((auth.jwt() ->> 'email') = 'lrinvl1203@gmail.com');

-- Purchases are written only by trusted server code using SUPABASE_SERVICE_ROLE_KEY.
drop policy if exists "Users can insert own purchases" on public.purchases;
